services:
  grpc-server:
    build:
      context: .
      dockerfile: grpc-server/Dockerfile
    container_name: grpc-server
    ports:
      - "50051:50051"

  grpc-client:
    build:
      context: .
      dockerfile: grpc-client/Dockerfile
    container_name: grpc-client
    depends_on:
      - grpc-server
